kind: pipeline
type: kubernetes
name: linux

platform:
  arch: amd64
  os: linux

steps:
- name: build
  image: golang:1.13
  commands:
  - echo 'hi'
  - pwd
  - go build -v ./cmd/livepeer/livepeer.go
