language: go
go:
- 1.11.x
os: osx
osx_image: xcode10.2
cache:
  directories:
  # We cache the SDK so we don't have to download it again on subsequent builds.
  - $HOME/google-cloud-sdk
env:
  global:
    - PKG_CONFIG_PATH=/Users/travis/compiled/lib/pkgconfig
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

script:
# These three lines needed so it works even if your name isn't "livepeer"
- cd $GOPATH/src/github.com
- mkdir -p ./livepeer
- mv "$TRAVIS_BUILD_DIR" "./livepeer/go-livepeer"
- cd ./livepeer/go-livepeer
- ./install_ffmpeg.sh
- ./install_dependencies.sh
- make livepeer livepeer_cli
- ./upload_build.sh
