language: go
go:
- 1.11.x
os: osx
osx_image: xcode10.2
env:
- PKG_CONFIG_PATH=/Users/travis/compiled/lib/pkgconfig
script:
# These three lines needed so it works even if your name isn't "livepeer"
- cd $GOPATH/src/github.com
- mkdir -p ./livepeer
- mv "$TRAVIS_BUILD_DIR" "./livepeer/go-livepeer"
- cd ./livepeer/go-livepeer
- ./install_ffmpeg.sh
- go get github.com/golang/glog
- go get -u -v github.com/ericxtang/m3u8
- go get github.com/aws/aws-sdk-go/aws
- go get -u google.golang.org/grpc
- go get github.com/pkg/errors
- go get github.com/stretchr/testify/mock
- go get -u -v go.opencensus.io/stats
- go get -u -v go.opencensus.io/tag
- go get -u -v contrib.go.opencensus.io/exporter/prometheus
- make
- './livepeer -version | sed "s/Livepeer Node Version: //" > version'
- mkdir livepeer-darwin-amd64
- mv ./livepeer livepeer-darwin-amd64
- mv ./livepeer_cli livepeer-darwin-amd64
- tar -czvf ./livepeer-darwin-amd64.tar.gz ./livepeer-darwin-amd64
- 'curl --fail -v --upload-file livepeer-darwin-amd64.tar.gz -H "Authorization: Bearer $GCLOUD_TOKEN" "https://storage.googleapis.com/build.livepeer.live/$(cat version)/livepeer-darwin-amd64.tar.gz"'
- 'curl --fail -H "Content-Type: application/json" -X POST -d "{\"content\": \"Build succeeded ✅\nBranch: $TRAVIS_BRANCH\nPlatform darwin-amd64\nhttps://build.livepeer.live/$(cat version)/livepeer-darwin-amd64.tar.gz\"}" $DISCORD_HOOK'
