language: go
go:
- 1.11.x
os: osx
osx_image: xcode10.2
env:
- PKG_CONFIG_PATH=/Users/travis/compiled/lib/pkgconfig
script:
- mkdir -p $GOPATH/src/github.com/livepeer
- ln -s $(pwd) $GOPATH/src/github.com/livepeer/go-livepeer
- ./install_ffmpeg.sh
- go get github.com/golang/glog
- go get -u -v github.com/ericxtang/m3u8
- go get github.com/aws/aws-sdk-go/aws
- go get -u google.golang.org/grpc
- go get github.com/pkg/errors
- go get github.com/stretchr/testify/mock
- go get -u -v go.opencensus.io/stats
- go get -u -v go.opencensus.io/tag
- go get -u -v contrib.go.opencensus.io/exporter/prometheus
- make
