# This is the one with Docker
image: Visual Studio 2017

# # Install scripts. (runs after repo cloning)
# install:
#   # Get the latest stable version of Node.js or io.js
#   - ps: Install-Product node $env:nodejs_version
#   # install modules
#   - npm install -g yarn
#   - yarn install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - ps: Write-Host "Install-Module DockerProvider"
  - ps: Install-Module DockerMsftProvider -Force
  - ps: Write-Host "Install-Package Docker"
  - ps: Install-Package -Name docker -ProviderName DockerMsftProvider -Force
  - docker build -m 4gb -t livepeer-windows -f .\docker\Dockerfile.windows .
  - docker run --name wlive livepeer-windows
  - docker cp wlive:c:/temp/livepeer-windows-amd64.zip .
  - docker rm wlive

# Don't actually build.
build: off
