# This is the one with Docker
image: Windows Server 2019

# # Install scripts. (runs after repo cloning)
# install:
#   # Get the latest stable version of Node.js or io.js
#   - ps: Install-Product node $env:nodejs_version
#   # install modules
#   - npm install -g yarn
#   - yarn install

# Post-install test scripts.
test_script:
  # - ps: Invoke-WebRequest -UserAgent 'AppVeyor CI' -outfile gcloud.zip https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-245.0.0-windows-x86_64-bundled-python.zip
  # - ps: Expand-Archive -path .\gcloud.zip -DestinationPath .
  # Borrowed from http://ec2-52-211-181-221.eu-west-1.compute.amazonaws.com/deploying-a-net-appengine-using-appveyor/
  - ps: $env:GCLOUD_TOKEN.length
  - ps: '[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:GCLOUD_TOKEN)) | Out-File token.json'
  - choco install gcloudsdk
  - refreshenv
  - gcloud.cmd components copy-bundled-python>>python_path.txt && SET /p CLOUDSDK_PYTHON=<python_path.txt && DEL python_path.txt
  - gcloud.cmd components update --quiet
  - gcloud.cmd auth activate-service-account --key-file=token.json
  - gsutil.cmd cp README.md gs://build.livepeer.live/README.md
  - docker build -m 4gb -t livepeer-windows -f .\docker\Dockerfile.windows .
  - docker run --name wlive livepeer-windows
  - docker cp wlive:c:/temp/livepeer-windows-amd64.zip .
  - docker rm wlive
  - gsutil.cmd cp livepeer-windows-amd64.zip gs://build.livepeer.live/test/livepeer-windows-amd64.zip

# Don't actually build.
build: off
