version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-builder
      - build:
          requires:
            - build-builder

jobs:
  build-builder:
    docker:
      - image: circleci/golang:1-stretch
    working_directory: /go/src/github.com/livepeer/go-livepeer

    environment:
      PKG_CONFIG_PATH: /root/compiled/lib/pkgconfig
      GOPATH: /go

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker pull iameli/nvidia-build:latest || echo 'no pre-existing cache found'
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: make nvidia-build
      - run: docker push iameli/nvidia-build:latest

  build:
    docker:
      # Note race condition - we might get the wrong builder if lots of builds are happening in
      # parallel because this pulls it down from Docker Hub.
      - image: iameli/nvidia-build:latest
    working_directory: /go/src/github.com/livepeer/go-livepeer

    environment:
      PKG_CONFIG_PATH: /root/compiled/lib/pkgconfig
      TEST_RESULTS: /tmp/test-results
      GOPATH: /go

    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      # - restore_cache:
      #     keys:
      #       - v3-pkg-cache

      - run:
          name: Lint
          command: |
            gometalinter --disable-all --enable=gofmt --enable=vet --enable=golint --deadline=4m pm

      - run:
          name: Compile binaries
          command: |
            make livepeer livepeer_cli

      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            /bin/bash test.sh 2>&1 | tee $TEST_RESULTS/go-test.out

      - run:
          name: Upload build
          command: ./upload_build.sh

      - save_cache:
          key: v3-pkg-cache
          paths:
            - "/go/pkg"
            - "/home/circleci/compiled"
            - "/home/circleci/nasm/nasm"
            - "/home/circleci/x264/x264"
            - "/home/circleci/ffmpeg/libavcodec/libavcodec.a"

      - store_test_results:
          path: /tmp/test-results
