version: 2
jobs:
  build:
    docker:
      - image: nvidia/cuda:10.1-devel-ubuntu18.04
    working_directory: /go/src/github.com/livepeer/go-livepeer

    environment:
        PKG_CONFIG_PATH: $HOME/compiled/lib/pkgconfig
        TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      # - restore_cache:
      #     keys:
      #       - v3-pkg-cache

      - run: apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:gophers/archive -y && apt-get update && apt-get -y install build-essential pkg-config autoconf gnutls-dev golang-1.11-go sudo git curl && mv /usr/lib/go-1.11/bin/* /usr/bin
      - run: ./install_ffmpeg.sh
      - run: ./install_dependencies.sh

      - run:
          name: Lint
          command: |
            gometalinter --disable-all --enable=gofmt --enable=vet --enable=golint --deadline=4m pm

      - run:
          name: Compile binaries
          command: |
            PKG_CONFIG_PATH=$HOME/compiled/lib/pkgconfig CPATH=/usr/local/cuda/include LIBRARY_PATH=/usr/local/cuda/lib64 make livepeer livepeer_cli

      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            PKG_CONFIG_PATH=$HOME/compiled/lib/pkgconfig /bin/bash test.sh 2>&1 | tee $TEST_RESULTS/go-test.out

      - run:
          name: Upload build
          command: ./upload_build.sh

      - save_cache:
          key: v3-pkg-cache
          paths:
            - "/go/pkg"
            - "/home/circleci/compiled"
            - "/home/circleci/nasm/nasm"
            - "/home/circleci/x264/x264"
            - "/home/circleci/ffmpeg/libavcodec/libavcodec.a"

      - store_test_results:
          path: /tmp/test-results
