# This script is downstream of build-linux and build-windows and works for both platforms.

# Don't mess with WORKDIR if you can avoid it, as it's different on Windows/Linux. Use relative
# paths instead.

FROM iameli/build-platform:latest

RUN curl https://sdk.cloud.google.com | bash > /dev/null

ADD ./install_ffmpeg.sh ./install_ffmpeg.sh
RUN ./install_ffmpeg.sh

ADD ./install_dependencies.sh ./install_dependencies.sh
RUN ./install_dependencies.sh

ADD . .
RUN make livepeer livepeer_cli
